# Generated by Django 3.0.5 on 2020-04-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_artist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
    ]
